// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJaktKWl5PlMzRhdgac1kFBXrvnv7LeMg',
    appId: '1:198028144277:web:5a90807bdc20f18ecbf59c',
    messagingSenderId: '198028144277',
    projectId: 'mayofyouth-8a080',
    authDomain: 'mayofyouth-8a080.firebaseapp.com',
    storageBucket: 'mayofyouth-8a080.firebasestorage.app',
    measurementId: 'G-V402MVKL29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAJngrc2Hbrms9-K0Cg0X-Ecu_naVIAk',
    appId: '1:198028144277:android:6e111a0f780564d7cbf59c',
    messagingSenderId: '198028144277',
    projectId: 'mayofyouth-8a080',
    storageBucket: 'mayofyouth-8a080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFmdrKuQb0hkEZHiAkx251vb82A-S6Q8',
    appId: '1:198028144277:ios:bc139f3df6a6fbadcbf59c',
    messagingSenderId: '198028144277',
    projectId: 'mayofyouth-8a080',
    storageBucket: 'mayofyouth-8a080.firebasestorage.app',
    iosBundleId: 'com.example.sam',
  );
}
